name: Weekly ADT Nightmare Problems Picker
on:
  schedule:
    - cron: "0 14 * * 6"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Run script
        run: python main.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add used_number.txt README.md
          if ! git diff --cached --exit-code; then
            git commit -m "[BOT] Update weekly numbers in README [skip ci]"
            git push
          fi
