name: Weekly ADT Nightmare Problems Picker
on:
  schedule:
    - cron: "0 14 * * 6"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run script
        run: python main.py # プログラム実行

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if ! git diff --exit-code used_numbers.txt; then
            git add used_numbers.txt
            git commit -m "Update history [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
